version: '3.4'

services:
  mysql:
    image: mysql:5.7.37
    container_name: my-mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_USER=my_root 
      - MYSQL_PASSWORD=my_pass 
      - MYSQL_ROOT_PASSWORD=my_pass 
      - MYSQL_DATABASE=alan_saputra_lengkoan
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  
  app:
    depends_on:
      - mysql
    container_name: my-app
    restart: always
    env_file: ./.env
    environment:
      - DB_HOST=mysql
      - DB_USER=my_root
      - DB_PASSWORD=my_pass
      - DB_NAME=alan_saputra_lengkoan
      - DB_PORT=3306
    ports:
      - '3030:3030'
    stdin_open: true
    tty: true